apiVersion: argoproj.io/v1alhpa1
kind: ApplicationSet
metadata:
  name: cluster-applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
      repoUrl: https://github.com/augustovictor/argocd-example-apps.git
      revision: HEAD
      directories:
        - product-teams/deployment/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: '{{.path.basename}}'
      source:
        repoUrl: https://github.com/augustovictor/argocd-example-apps.git 
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true

