apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustom-guestbook
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/augustovictor/argocd-example-apps.git
    path: guestbook
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
