apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-applications
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/augustovictor/guestbook-argocd-lab.git
      revision: HEAD
      directories:
        - path: product-teams/deployment/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/augustovictor/argocd-example-apps.git 
        targetRevision: HEAD
        path: '{{path.basename}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

